export const students = [
  {
    stt: 1,
    mssv: "B200001",
    ten: "Nguyễn Văn A",
    gt: "Nam",
    dc: "Cần Thơ",
    dt: "0123456783",
    email: "nva@gmail.com",
    tt: "Còn học",
  },
  {
    stt: 2,
    mssv: "B200002",
    ten: "Nguyễn Văn B",
    gt: "Nam",
    dc: "Cần Thơ",
    dt: "0123456782",
    email: "nvb@gmail.com",
    tt: "Còn học",
  },
  {
    stt: 3,
    mssv: "B200003",
    ten: "Nguyễn Thị C",
    gt: "Nữ",
    dc: "Cần Thơ",
    dt: "0123456783",
    email: "ntc@gmail.com",
    tt: "Tốt nghiệp",
  },
];
